core/urls.py
from django.urls import path
from .views import index, get_urls, entry_list


app_name = 'core'
urlpatterns = [
    path('', index, name='index'),
    path('get-urls/', get_urls, name='get-urls'),
    path('entry-list/', entry_list, name="entry-list")
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('receiver/', include('receiver.urls', namespace='receiver')),
    path('', include('core.urls', namespace='core'))
]

receiver/urls.py
from django.urls import path
from .views import receiver_room

app_name = 'receiver'
urlpatterns = [
    path('<room_name>/', receiver_room, name="receiver")
]

core/models.py
from django.db import models


# class EntryManager(models.Manager):
#     def get_queryset(self):
#         return super(EntryManager, self).get_queryset().order_by('-timestamp')


class Entry(models.Model):
    url = models.URLField(max_length=300)
    status_code = models.CharField(max_length=10)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)

    # objects = EntryManager()

    def __str__(self):
        return self.url

receiver/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from .models import Entry
from .tasks import fetch_links
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

# rest_framework imports
from rest_framework.generics import ListAPIView


def index(request):
    template_name = 'core/index.html'
    return render(request, template_name)


def entry_list(request):
    template_name = 'core/entry_list.html'
    return render(request, template_name,
                  {'entry_list': Entry.objects.all()})


def get_urls(request):
    url = str(request.GET.get('url'))
    fetch_links.delay(url)
    return HttpResponseRedirect(
        reverse_lazy('core:entry-list'))

receiver/views.py
from django.shortcuts import render


def receiver_room(request, room_name):
    return render(request,
                  'receiver/room.html',
                  {'room_name': room_name})

core/templates/core/entry_list.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-lg-6">
            <h3>We collect urls from this site</h3>
            <h5 class="mb-5">Please wait...</h5>
            <div class="">
                <a class="btn btn-outline-info" href="{% url 'core:index' %}">Back to main</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/core/index.html
{% extends 'base.html' %}
{% block title %}index{% endblock title %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 mt-5">
      <h2>Fill form with some url</h2>
      <form class="mt-4" action="{% url 'core:get-urls' %}" method="get">
        <div class="form-group d-flex">
          <label class="sr-only" for="urlFieldInput">Url</label>
          <input id="urlFieldInput" class="form-control " name="url" type="text" placeholder="Enter url...">
          <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
      </form>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <ul class="list-unstyled ml-4">
        {% for key in object_list %}
          <li>
            [<small>{{ key.timestamp|date:"SHORT_DATE_FORMAT" }} at {{ key.timestamp|time }}</small>]
            [<small class="text-muted">{{ key }}</small>]
            [{{ key.status_code }}]
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>



{% endblock content %}

receiver/templates/receiver/room.html
{% extends 'base.html' %}
{% block title %}Receiver room{% endblock title %}
{% block content %}
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'nav.html' %}
    {% block content %}{% endblock content %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse text-center" id="navbarNav">
    <ul class="list-unstyled mx-auto my-3">
      <li class="">
        <a class="nav_a" href="#">Home</a>
      </li>
      <li class="mt-2">
        <a class="nav_a" href="#">Features</a>
      </li>
      <li class="mt-2">
        <a class="nav_a" href="#">Pricing</a>
      </li>
    </ul>
  </div>
</nav>
<style>
    {% comment %} .nav_ul {
        margin-top: 25px;
        margin-bottom: 35px;
    } {% endcomment %}
    .nav_a {
        font-size: 17px; 
        color: white;
        opacity: 1;
    }
    .nav_a:hover {
        color: white;
        opacity: 0.7;
        text-decoration: none;
    }
</style>